version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"


  tests:
    build: .
    command: pytest tests/ -v
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
    depends_on:
      - api